# <font color = 'red'> Solutions for </font>Exercises for Lab 01 <font color = 'blue'>Version 1.0</font>

Hello and welcome to the Exercises! These are a series of supplemental problems designed to get you fluent in Python, and which cover material from Lab 01 to Lab 05. Since you're just starting out with the process of learning Python, this Exercise in particular will aim to provide some basic groundwork that will help you greatly in your later labs.

## The Syntax of Python
Python, like all computer languages, adheres to a very strict set of rules regarding how code is written and interpreted. All of the code you write will be a combination of four main code structures.

|Name|Structure|Example|Purpose|
|--|--|--|--|
|Operation|`object1 <operator> object2`|`a + b`|Create a new value that is a modification of a and b given the operator specified.|
|Function|`functionName(arguments)`|`print(a, b)`|Take in some inputs (called arguments) and do something with them as befit its design. Functions are by far the most versatile and most common of the four structures, so expect lots of variety.|
|Method|`object.methodName(arguments)`|`a.replace(b, c)`|A specialized version of the function; it modifies the object as befit its design AND any specifications described in the arguments.|
|Index|`object[position]`|`a[b]`|Spoiler for lab 02; this is for data types that are a sequence of characters (e.g. strings, lists, arrays). The index concerns the position of each term in the sequence.|

Note that in the wild, these structures are not limited to their forms as described in the table. You can have a method with no arguments, and indices that specify more than one position. However, even with such variations, these structures remain remarkably close to the purposes as specified here. Moreover, and this is VERY common, these structures will be nested within each other. For example, `functionName(a[b])`; in this case, the innermost (the index) is evaluated first, and that becomes the argument for the function.

As a baseline rule, do NOT mix up these structures with any variables you create. If you name a variable the exact same thing as a function or method name, python will become very confused and you will likely be unable to use that function/method again unless you restart the kernel.

## An intro to Importing Libraries

In [1]:
import numpy as np
import matplotlib
import math as m
from datascience import *

The above 'importing' of these libraries, as they are called, is akin to the unlocking of a whole new set of functions, methods, and other workings to be used in your code. If you do not include and run these imports, you won't have access to these tools.

These additional tools' appearances depend on how you import them. Specifically, their functions typically appear with the name of their library before it. For example, since we imported numpy as np, its functions have 'np' before it. See below for examples.

In [2]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [3]:
arange(5)

NameError: name 'arange' is not defined

In [8]:
import numpy
numpy.arange(5)

array([0, 1, 2, 3, 4])

See how, since we imported numpy again but with no clarification on its name, we can thus use its full name 'numpy' before the function name. (Since we also imported it as 'np' earlier, the 'np.arange' format still works.)

This means you can technically use anything under the sun as the name of a library.

In [4]:
import numpy as tomato
tomato.arange(5)

array([0, 1, 2, 3, 4])

If you really REALLY want to import the library without its name, it requires a bit of formatting and the use of an asterisk. This is super risky, however, and should be used only if there are very few functions in the library (like in the Datascience module.)

In [5]:
from numpy import *
arange(5)

array([0, 1, 2, 3, 4])

This 'from (method) import (function)' can be used to render specific functions without their module name. If I run the cell below this without having done what I did in the previous cells, only arange would be able to be used without its module name, and all other functions would NOT be imported.

In [6]:
from numpy import arange
arange(5)

array([0, 1, 2, 3, 4])

You can find additional info on any library by typing in any of its defined names (in this case np, numpy, and tomato are all available since we assigned them all to this numpy library earlier) with a question mark.

In [7]:
tomato?

Type:        module
String form: <module 'numpy' from '/opt/conda/lib/python3.11/site-packages/numpy/__init__.py'>
File:        /opt/conda/lib/python3.11/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

U

You can also do help(library name), but I do caution you against it because of just how comprehensive it is. Instead, you can see that they provide external resources and other assistance with the library in the cell output we just saw.

Note the similarity between the library functions and the method structure, namely that both consist of a word before the function/method name. Since you are only working with a select few libraries (matplotlib, numpy, datascience, EDS), it will be relatively easy to tell them apart. However, keep in mind that library functions do not do anything with their library once imported, while any methods, library or otherwise, are designed to modify their specified objects.

## Exercise 1: Breaking the Ice
A big trouble we often see is that it takes a lot of practice to move from the highly generalized structure as shown above to the wide and wacky world that is actual coding. Thus, this section will be devoted to showing you some small examples of these structures.

### 1.1:
Consider the following:

`string.upper()`

What kind of structure is it? **Method**

Given this structure's purpose, and its name here, what do you think this code will do? **It acts on the string (purpose of the method) to make it uppercase (name).**

Create a string in the cell below, and type in the code to see what it does to the string.

In [9]:
string = 'test'

string.upper()

'TEST'

### 1.2:

Remember, you must untether yourself from the `string` part of the code. Any string, of any variable name, can replace it.

I have prepared several strings for you; use `.upper()` on it.

In [10]:
fun = 'wheeee'

fun.upper()

'WHEEEE'

In [11]:
danger = 'caution'

danger.upper()

'CAUTION'

In [12]:
truth = 'python is easy :)'

truth.upper()

'PYTHON IS EASY :)'

### 1.3:

Uh oh, looks like we were a bit too enthusiastic in beginning the new semester. Help us tone it down by thinking of a method that does the *opposite* of `.upper()`.

In [13]:
welcome_message = 'HEY CODERS! WELCOME TO THE COURSE!'

welcome_message.lower()

'hey coders! welcome to the course!'

## Exercise 2: PEMDAS
Here are a couple mathematical expressions that you'll need to convert to math form. Write it out in the cells below and have the computer calculate it for you. PLEASE don't do hand calculations. After all, the purpose of Python here is to do all the nitty-gritty work for you. Try using variables to stand in for various parts of the math problems; refer to 2.1 for an example.

Some of these will become progressively more difficult. Again, resist the urge to pull out your calculator or some scrap paper. Use plenty of variables if you must, but trust in Python to do the hard work for you.

For your reference, here is a table of the operators that you'll need. Unless otherwise stated, a and b are integers or floats.

|Name|Operator|Effect|
|--|--|--|
|Addition|`a + b` (where a and b are integers or floats)|Adds a and b together|
|Concatenation|`a + b` (where a and b are strings)|Joins a and b side by side|
|Subtraction|`a - b`|Subtracts b from a|
|Multiplication|`a * b`|Multiplies a and b together|
|Division|`a / b`|Divides a by b|
|Exponentiation|`a**b`|Raises a to the power of b (In effect, multiplying a by itself b times)|
|Modulus|`a % b`|Gets the remainder when a is divided by b|

### 2.1: 
The sum of eighty-three and twenty-seven, all of which is divided by five.

In [14]:
sum = 83+27
e2_1 = sum/5
e2_1

22.0

### 2.2: 
The remainder when the square of the sum of six and twelve is divided by the product of twenty and three-fourths.

In [16]:
# i'll split these into parts. students dont have to split it as such.
part1 = 6+12
part2 = 20*(3/4)

e2_2 = (part1**2)%part2
e2_2

9.0

### 2.3: 
The first five positive prime numbers concatenated together, divided by the product of 151 and 223.

In [19]:
part1 = '2'+'3'+'5'+'7'+'11'
part2 = 151*223

e2_3 = int(part1)/part2
e2_3

7.0

### 2.4: 
The remainder when the first three positive squares concatenated together are divided by their sum.

In [21]:
part1 = '1'+'4'+'9'
part2 = 1 + 4 + 9

e2_4 = int(part1)%part2
e2_4

9

### 2.5: 
The approximate result when two is raised to the quotient of the sum of forty-three and eighty-four and the sum of thirty three and a third. Use `round(...)` to get the nearest integer.

In [22]:
part1 = 43+84
part2 = 33+1/3

e2_5 = round(2**(part1/part2))
e2_5

14

### 2.6: 
The approximate speed of 11.18 mph converted to m/s. 1 mph = 0.447 m/s. 

In [23]:



e2_6 = round(11.18*0.447)
e2_6

5

### 2.7: 
The total of 1 dollar, 21 half-dollars, 20 quarters, 8 dimes, 15 nickels and 18 pennies, rounded to the nearest dollar. (Key?)

In [25]:


e2_7 = round((1 * 1) + (21 * 0.5) + (20 * 0.25) + (8 * 0.1) + (15 * 0.05) + (18 * 0.01))
e2_7

18

### 2.8: 
The difference between the sum of the solutions to the first four problems and the sum of the solutions of the last three ones, all divided by 2. (ONLY use variables.)

In [26]:
e2_8 = ((e2_1 + e2_2 + e2_3 + e2_4) - (e2_5 + e2_6 + e2_7))/2
e2_8

5.0

## Exercise 3
This part is about formulae used in various subjects. Because of the arithmetic nature of Python's floats and integers, you can simply create an equation using variables, assign values to these variables, and run the equation to get a new value.

Position of a ball as a function of time.

$$y = -\frac12gt^2+v_0t+h_0$$

As you throw an object upwards, its position (y) will depend on the time after your throw, as well as the following.
* $g$: the acceleration due to gravity ($32.2 ft/s^2$ or $9.8 m/s^2$, depending on units)
* $v_0$: the initial upward velocity exerted by your hand
* $h_0$: the initial height (relative to some zero-level) at which the object leaves your hand



### 3.1: 
Express this equation with the variables as shown. (use v and h for $v_0$ and $h_0$.)

Note that you can't just place two variables next to each other to multiply them. I've assigned placeholder values for g, h, and v only so that you don't get an error message when you make the equation.

In [27]:
g = 9.8
v = 0 # these values will change later
h = 0
t = 0
y = -1/2 * g * t**2 + v * t + h

### 3.2: 
Imagine that you throw the object at a starting velocity of 28 m/s and at a height of 0.1 meters. What is the position after 3 seconds? (After assigning your variables, simply copy and paste the equation from above into the cell below this.)

In [28]:
g = 9.8
v = 28
h = 0.1
t = 3
y = -1/2 * g * t**2 + v * t + h # copy and paste the equation from above
print(y)

40.0


### 3.3: 
Imagine now that that you throw the ball again at a position of 0 feet, and it returns to your hand after 6.5 seconds. However, you were lifting weights earlier and your sore arm gives you no indication of how much speed you had given the ball. Rearrange the equation in terms of v and plug in the variables to find the starting velocity of this throw. Have you grown stronger or weaker since your first throw?

In [29]:
g = 32.2 # feet units
h = 0
t = 6.5
y = 0
v = (y + 1/2 * g * t**2 - h) / t # rearrange the equation for v
print(v)

104.65


In [30]:
# 104.65 ft/s > 91.9 ft/s (28 m/s to ft/s); you got stronger.

### 3.4: 
Imagine that you're playing tennis. To serve a ball, you have to toss it up and hit it with your racket and your outstretched arm. You throw the ball with a velocity of 5 m/s and a height of 1 meter. The combined length of your outstretched arm and the racket is at a position 0.75 meter above that. At what two times can you hit the ball to make a decent serve? (This is a challenge problem! it's ok if you don't do this one.)

In [40]:
g = 9.8
v = 5
h = 1
y = 1.75
t1 = (-v + (v**2 + 2 * g * (h - y))**0.5)/(-g) # rearrange the equation for the two values of t (this may be a bit hard to do.)
t2 = (-v - (v**2 + 2 * g * (h - y))**0.5)/(-g)
print(t1, t2)

0.18271823396160794 0.837689929303698


### 3.5: 
Imagine that you are outside throwing a ball really high up in the air. Suddenly, you realize that the trajectory of the ball will direct it right on the roof of your parent's car. You had thrown it with a starting velocity of 120 ft/s (impressive!) at a height of 0 ft, and the car roof is located 1.5 ft above the height of your throwing position. How much time do you have, from the moment you threw it to the moment it lands, to run over and catch the ball before it dents the car?

(This is also a challenge. You're fine to not do this as well.)

In [41]:
# use the format above to define the variables
# then copy and paste the expressions for t1 and t2 here
g = 32.2
v = 120
h = 0
y = 1.5
t1 = (-v + (v**2 + 2 * g * (h - y))**0.5)/(-g)
t2 = (-v - (v**2 + 2 * g * (h - y))**0.5)/(-g)
print(t1, t2)

0.012521034153081876 7.44089511491524


## The End?
This marks the end of the Exercises 01. These Exercises are still in their relative infancy, and we are constantly improving upon them to make the coding experience smoother. How useful are these Exercises in that regard? Are they of the appropriate difficulty? Are there any points of misunderstanding that we haven't addressed? Feel free to leave your feedback below.

Oh right; just below we have a secret code!

fik tm galm p yeoq gvhyihz dwkh ugf qvrntpbky, vna hye mbnvk oz mos jtukz arkyl ts urytt

look throughout the Exercises 01 to find what to do with it. ;) 

Enter the right stuff below to maybe get some more extra credit!

<details>
    <summary>This is the solution for the Extra Credit of Exercises 01. Do not click if you do not want to be spoiled.</summary>
    The Exercise 2 answers, when put through an a1z26 decoder, spell out VIGINERE. Exercise 2.7 has numbers pertaining to the different coin values, and in that order, they spell out AUTHOR when put through the same a1z26 decoder. Thus, the above jumbled text is to be put through a viginere decoder (easily searchable on the internet), where the key is AUTHOR, and the decoded version is the quote by vincent van gogh: FOR MY PART I KNOW NOTHING WITH ANY CERTAINTY, BUT THE SIGHT OF THE STARS MAKES ME DREAM. Since the AUTHOR key implies that the author of the quote is desired, the correct final code is VAN GOGH, or VINCENT VAN GOGH.
</details>