# <font color=red> Solutions for</font> Exercises for Lab 02: <font color=blue>Version 1.1</font>
Welcome to the Exercises for Lab 2! Completion of this will net you THREE extra credit points! There might be more around here, though.

In [1]:
import numpy as np
from datascience import *

## Lists and Arrays

Lists and Arrays are extremely similar in how they work. Being two of the most-used data types in this program, it is imperative that you get a hold on what is a list vs what is an array, and how they differ in appearance, use, and other aspects.

Note: a component of a list or array is called an element. The placement of an element in a list or array, with the first being designated as 0, the second as 1, and so on, is the Index of the element.

Any and all parts of the code intended to be customizable as befit the situation (e.g. what list are you trying to append stuff to? what variable is this stuff defined as?) has a capital letter (Functions/Methods like these do not use capital letters).

Use this following Table as your toolbox for any and all functions involving lists and arrays; you can refer to these at any time during your Labs and Exercises, and may even find it useful to add to these if you encounter something new!

|Descriptor|List|Array|
|--|--|--|
|How to make it:|simply type in the list elements as following:`ListName = [Element1, Element2, Element3, ...]`|use the datascience module command `ArrayName = datascience.make_array(Element1, Element2, Element3, ...)` or, if it is a sequence of numbers, `ArrayName = np.arange(Start, End, Step)` (Start and end are optional; omit them if you are going from 0 and up by 1)|
|Composition:|accepts most if not all data types wherever|accepts most of not all data types, but a single array must have only one data type|
|Location in a Table (spoiler for Lab 3!):|a single row of a table|a single column of a table, minus the header row|
|How to convert...|From an Array to a List: `list(Array)`|From a List to an Array: `np.array(List)`|

List of commands:

|Effect|List|Array|
|--|--|--|
|Getting the Index of an Element|`ExistingList.index(Element)` (this only gives you the first occurrence as an integer datatype)|`np.where(ExistingArray == Element)` (gives you an array of all the indexes the target Element is found)|
|Getting an Element from its Index|`ExistingList[IndexOfElement]`|`ExistingArray[IndexOfElement]`|
|Adding an element to it|`ExistingList = ExistingList + [NewElement]` or `ExistingList.append(NewElement)`|`ExistingArray = np.append(ExistingArray, NewElement)`|
|Removing an element|`ExistingList.remove(Element)` or `del ExistingList[IndexOfElement]` or `ExistingList.pop(IndexOfElement)`|`ExistingArray = ExistingArray.delete(IndexOfElement)`|
|Changing a specific element|`ExistingList[IndexOfTargetElement] = NewElement`|`ExistingArray[IndexOfTargetElement] = NewElement`|
|Modifying all elements by the same operation/function/method (this works for all of these three; I'll use the abbreviation FOM for where you should put this) (There are a few examples below)|`[FOM(x) for x in List]`|`[FOM(x) for x in Array]` (output is a list) OR `FOM(Array)` (output is an array)|
|Exclusive for Lists: Modifying/Filtering with a Conditional|`[FOM(x) for x in List if ...]` (`...` is where you put the conditional statement, like `x == 5` or `x <= 3`) OR `[x for x in List if ...]` to get only the elements of the list that match that conditional (filtering)|Replace the list with an array to filter it. However, the output will be an list.|

|Effect|Function|
|--|--|
|average|`np.average(listOrArray)`|
|maximum|`max(listOrArray)`|
|minimum|`min(listOrArray)`|
|sum|`sum(listOrArray)`|
|length (number of elements)|`len(listOrArray)`|

|Conditional|Meaning|
|--|--|
|`x == a`|Is x equal to a?|
|`x != a`|Is x not equal to a?|
|`x > a`|Is x greater than a?|
|`x < a`|Is x less than a?|
|`x >= a`|Is x greater than or equal to a?|
|`x <= a`|Is x less than or equal to a?|
|`x in a`|Is x contained within a (in the situation where a is a list/array/string)?|

In conditionals, you can modify x and a to suit the situation. For example, `x % 2 == 1` gives a True if the remainder of x when divided by 2 is 1.

### Lists: Element Manipulation
Lists are more data oriented. They typically treat their elements the same regardless of data type. Multiplying by two doesn't double the values of any floats or integers, but instead repeats the composition of the list again.

In [2]:
list1 = [52, 23, 66]
list1*2

[52, 23, 66, 52, 23, 66]

Concatenation and Mathematical operations: You must specify that you are doing this operation to each element in the list.

In [3]:
list2 = ['hope', 'delight', 'doubt']
[i+'ful' for i in list2]

['hopeful', 'delightful', 'doubtful']

In [4]:
[i*2 for i in list1]
# example of a math operation being done on all elements

[104, 46, 132]

In [5]:
[len(x) for x in list2]
# example of a function being done on all elements

[4, 7, 5]

In [6]:
list3 = ['Panama Canal', 'Banana', 'Appalachians']
[x.split('a') for x in list3]
# example of a method being done on all elements

[['P', 'n', 'm', ' C', 'n', 'l'],
 ['B', 'n', 'n', ''],
 ['App', 'l', 'chi', 'ns']]

The `[x for x in List]` format serves as an operation in itself, and can be done for sublists and subarrays within lists (but it's quite trippy).

In [7]:
list4 = np.arange(1,11) # numbers from 1 to 10
listception = [np.arange(0,x) for x in list4]
listception

[array([0]),
 array([0, 1]),
 array([0, 1, 2]),
 array([0, 1, 2, 3]),
 array([0, 1, 2, 3, 4]),
 array([0, 1, 2, 3, 4, 5]),
 array([0, 1, 2, 3, 4, 5, 6]),
 array([0, 1, 2, 3, 4, 5, 6, 7]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])]

In [8]:
plus1_listception = [[y+1 for y in x] for x in listception] # that is, add 1 to all the terms for each sublist in the listception
plus1_listception

[[1],
 [1, 2],
 [1, 2, 3],
 [1, 2, 3, 4],
 [1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5, 6],
 [1, 2, 3, 4, 5, 6, 7],
 [1, 2, 3, 4, 5, 6, 7, 8],
 [1, 2, 3, 4, 5, 6, 7, 8, 9],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]

### Arrays: Element Manipulation
It might help to think of arrays as being more numerically oriented. Any mathematical operations on arrays made of floats or integers behave as though the operation is being done on each element individually.

Concatenation and Mathematical Operations: Since Arrays treat numbers like math, you can do any mathematical operations to the array itself, and it will apply to all terms inside.

In [9]:
array1 = make_array(52, 23, 66)
array1*2

array([104,  46, 132])

You can still use the same thing for lists as for arrays, but the output here is a list.

In [10]:
[x**2 for x in array1]

[2704, 529, 4356]

Concatenation works slightly differently, but it is still noticeably easier on arrays than on lists.

In [11]:
array2 = make_array('animate', 'corroborate', 'disguise', 'orientate')
array2 = np.char.add(array2,'d')
array2

array(['animated', 'corroborated', 'disguised', 'orientated'],
      dtype='<U12')

Operations between Arrays is only possible if both have the same number of elements.

In [12]:
array3 = make_array(1,2,3)
array4 = make_array(5,6,7)
array3*array4 # the nth term of array3 is multiplied with the nth term of array4

array([ 5, 12, 21])

### Arrays as containing only One Datatype
The Numpy Array's main difference from lists is that it limits itself to only one datatype, and any new datatype added to it will cause the array's elements to modify themselves to match a common datatype.

Example: An array made of arrays.

In [13]:
from datascience import *
test1 = make_array('blah', 'blah', 'blah')
test2 = make_array('stuff', 'stuff', 'stuff')
arr = make_array(test1, test2) # array containing two arrays!
print('The First Element here is a', str(type(arr[1])))
print('The Length of this array is', len(arr))
arr

The First Element here is a <class 'numpy.ndarray'>
The Length of this array is 2


array([['blah', 'blah', 'blah'],
       ['stuff', 'stuff', 'stuff']], dtype=object)

If you add another element of a different datatype, the array will accept it, but it will modify its elements such that all of them are the same datatype.

Exhibit 1: arr had arrays previously. If I add a string, the arrays inside are broken apart into their separate strings.

In [14]:
arr = np.append(arr, 'this is a string, not an array.') # adding a string to the array of arrays
print('The First Element here is a', str(type(arr[1])))
print('The Length of this array is', len(arr))
arr

The First Element here is a <class 'str'>
The Length of this array is 7


array(['blah', 'blah', 'blah', 'stuff', 'stuff', 'stuff',
       'this is a string, not an array.'], dtype=object)

Exhibit 2: making an array consisting of a string, an integer, and a float turns all elements into strings. Note that it does this because a string can't reliably be converted into floats or integers the same way floats and integers can be converted into strings.

In [15]:
test3 = make_array('this is a string.', 3, 5.0)
print('The Integer 3 became a', type(test3[1]))
test3

The Integer 3 became a <class 'numpy.str_'>


array(['this is a string.', '3', '5.0'],
      dtype='<U32')

## Strings
Strings are one of the three main datatypes alongside floats and integers. While those two are fairly straightforward, the string is more complex because it behaves not like a single character or an inseparable cluster thereof, but rather a sequence in the same way that lists and arrays are sequences of characters.

See the table below for a list of functions.

|Function|String|
|--|--|
|How to get the Element of a certain Index|`existingString[indexOfElement]`|
|How to add Strings together (concatenation)|`newString = existingString+existingString`|
|How to replace elements of a string with another|`existingString = existingString.replace(oldElement, newElement, numberOfOldElementsToBeDeleted)` (number is optional; if the number is 2, then two of the oldElements will be deleted, and any more won't)|
|How to delete elements from a string|use the above .replace function, but with the newElement being simply an empty quotation|
|How to take a certain region of the string|`newString = existingString.split(boundaryElement)[indexOfTargetSection]` or `newString = existingString[startingIndex:finishingIndex]` (leave the starting or finishing index blank if going from the beginning or going to the end)|
|How to calculate a mathematical expression in String format|`eval(mathExpressionAsString)`|
|How to split up a string|`existingString.split(splitBoundaryAsString)` (this consumes the split boundary and returns a list of the resultant pieces)|

In [16]:
apple = 'apple'
apple = 'h'+apple.replace('p', 'g')
apple

'haggle'

In [17]:
One_and_a_half = '2*3/4'
eval(One_and_a_half)

1.5

## Indices!

Indices are one of the most essential components in Python, because they work with lists, arrays, strings, and (for Lab 03) Tables as well. They are specific integers that represent the position of the terms in the list or array or string. They don't count from 1, but 0 instead. So the 'first' term has an index of 0, the 'second' term has an index of 1, and so forth. See below for the format of these indices.

In [18]:
soups = ['alphabet', 'chicken', 'noodle', 'italian wedding', 'tomato']
soups[0] # this outputs the first term of soups

'alphabet'

In [19]:
soups[:3] # the colon represents a range; what we're doing is selecting from the start all the way up to (but not including) the term of index 3

['alphabet', 'chicken', 'noodle']

In [20]:
soups[-1] # going in the negative direction is akin to starting from the last term and working backwards.

'tomato'

Strings are also 'lists' of characters, so taking an index gets the nth letter in that string (counting spaces as well). 

In [21]:
word = 'example'
word[0] # indices always start from 0 regardless of the data type.

'e'

In [22]:
soups[3][1] # the first index gets the term of index 3 ('italian wedding'); the second index gets the letter of index 1 in 'italian wedding'.

't'

The integers that make up indices are no different from any other integer, and can be modified so long as it remains an integer.

In [23]:
soups[2+3-1]

'tomato'

## The Actual Exercises
Go through these tasks with the intention of doing things step by step, and refer back to the toolboxes up above. Note that ALL exercises here can be done using only the contents of the toolboxes. Please refrain from using AI :<

### Exercise 1: Odd Numbers

1.1: You can express any odd number as the difference of the two squares of consecutive integers. For example, the difference between 4<sup>2</sup> and 5<sup>2</sup> is 9. Use this fact to create a list of the first 100 positive odd numbers; start from an array of the first 100 numbers (both odd and even). Store your result under the variable name `e1_1`.

Hints:
* What's a super concise way of generating a hundred numbers?
* If any number in the array is `x`, how do you represent the number that is one above it?

In [24]:
numbers = np.arange(100)
e1_1 = [(x+1)**2-x**2 for x in numbers]
print(e1_1)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99, 101, 103, 105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129, 131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155, 157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181, 183, 185, 187, 189, 191, 193, 195, 197, 199]


1.2: You can also express any odd number as the formula `2n+1`, where n is a whole number integer. Use this to generate a list of the first 100 positive odd numbers, and store that under `e1_2`.

In [27]:
e1_2 = [2*x+1 for x in numbers]
print(e1_2)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99, 101, 103, 105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129, 131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155, 157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181, 183, 185, 187, 189, 191, 193, 195, 197, 199]


1.3: Of course, you can always take the simple route and filter a list of numbers based on oddness/evenness. Use a list of the first 200 integers to get a list of the first 100 positive odd numbers, and store that under `e1_3`. Hint: when using the `if` filtering, the double equals signs `==` means that the two sides are alike (in contrast to a single equals sign, which is for assigning values to variables).

In [28]:
e1_3 = [x for x in np.arange(200) if x%2==1]
print(e1_3)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99, 101, 103, 105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129, 131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155, 157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181, 183, 185, 187, 189, 191, 193, 195, 197, 199]


1.4: And perhaps the easiest way, you can just use `np.arange` and a step size of two to generate the odd numbers.

In [29]:
e1_4 = np.arange(1, 200, 2)
print(e1_4)

[  1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71
  73  75  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107
 109 111 113 115 117 119 121 123 125 127 129 131 133 135 137 139 141 143
 145 147 149 151 153 155 157 159 161 163 165 167 169 171 173 175 177 179
 181 183 185 187 189 191 193 195 197 199]


1.5: Here's a challenge: You've done all four problems above and want to check whether all of the resulting arrays/lists are equal to each other. However, you are not in the mood to look through 400 numbers. How can you make the computer check them for you?

Hints:
* You'll want to look at two lists/arrays at a time. Maybe check e1_1 & e1_2, then e1_2 & e1_3, and lastly e1_3 & e1_4.
* Using a Conditional to see if two Lists are the same gives a single True or False. However, if any of them is an array, you'll get an array of True's and False's instead (one for each term). These arrays of True's/False's are a bit of a hassle to deal with (but you'll use them in Exercise 2.3!), so it's much easier to convert any arrays to lists and compare Lists to Lists. How can you do that?

In [30]:
e1_1 == e1_2

True

In [31]:
e1_2 == e1_3

True

In [33]:
e1_3 == list(e1_4)

True

1.6: Lastly, take any of the four lists/arrays from before, and, in a single line of code, get only those that are 2 above a multiple of 7.

In [34]:
e1_6 = [x for x in e1_1 if x%7==2]
e1_6

[9, 23, 37, 51, 65, 79, 93, 107, 121, 135, 149, 163, 177, 191]

### Exercise 2: Prime Numbers
2.1: The square of any Prime Number greater than 3 is one more than a multiple of 24. For example, 5<sup>2</sup> is 25, which is `24*1+1`, and 7<sup>2</sup> is 49, which is `24*2+1`. In essence, p<sup>2</sup> = 24n+1, where n is any integer. Solve this for p, and then generate the first 19 primes in this formula by starting with an array of 200 integers (you'll see why we need so many!) from 1 to 200. Make sure to avoid 0 in that initial array.

In [36]:
# p=sqrt(24n+1)
p24 = [(24*x+1)**0.5 for x in np.arange(1,201)]
print(p24)

[5.0, 7.0, 8.5440037453175304, 9.8488578017961039, 11.0, 12.041594578792296, 13.0, 13.892443989449804, 14.730919862656235, 15.524174696260024, 16.278820596099706, 17.0, 17.691806012954132, 18.357559750685819, 19.0, 19.621416870348583, 20.223748416156685, 20.808652046684809, 21.377558326431949, 21.931712199461309, 22.472205054244231, 23.0, 23.515952032609697, 24.020824298928627, 24.515301344262525, 25.0, 25.475478405713993, 25.942243542145693, 26.40075756488817, 26.851443164195103, 27.294688127912359, 27.730849247724095, 28.160255680657446, 28.583211855912904, 29.0, 29.410882339705484, 29.816103031751148, 30.215889859476256, 30.610455730027933, 31.0, 31.384709652950434, 31.764760348537184, 32.140317359976393, 32.511536414017719, 32.878564445547191, 33.241540277189323, 33.600595232822883, 33.955853692699286, 34.307433596816885, 34.655446902326908, 35.0, 35.341194094144583, 35.679125549822544, 36.013886210738214, 36.345563690772494, 36.674241641784491, 37.0, 37.322915213043039, 37.6430604

You may realize that not all of the terms in there are whole numbers. Try and filter them such that only the whole numbers remain. Name the filtered list `e2_1`.

In [37]:
e2_1 = [x for x in p24 if x%1 == 0]
print(e2_1)

[5.0, 7.0, 11.0, 13.0, 17.0, 19.0, 23.0, 25.0, 29.0, 31.0, 35.0, 37.0, 41.0, 43.0, 47.0, 49.0, 53.0, 55.0, 59.0, 61.0, 65.0, 67.0]


Make sure to store your list as `e2_1`, then use the following cell to check against a preset list of primes. Are there any imposters? How can you get rid of them?

In [38]:
# just run this
preset_primes = [5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67]
trouble_spots = []
for i in e2_1:
    if np.count_nonzero([n == i for n in preset_primes]) == 1:
        pass
    else:
        trouble_spots.append(i)
trouble_spots

[25.0, 35.0, 49.0, 55.0, 65.0]

2.2: In Prime Numbers, a classic is what is known as Euler's Lucky Numbers (or Caboose Numbers), which are integers p such that $x^2-x+p$ gives prime numbers when x is any integer from 0 to p-1. The most famous Euler Lucky Number is 41; that is, for all integers from 0 to 40, this expression $x^2-x+41$ gives primes.

Since this is so similar to problems like Exercise 1, I challenge you to get the 41 primes that can come from the expression $x^2-x+41$ in just ONE line of code. Good luck!

In [40]:
e2_2 = [x**2-x+41 for x in np.arange(1,41)]
print(e2_2)

[41, 43, 47, 53, 61, 71, 83, 97, 113, 131, 151, 173, 197, 223, 251, 281, 313, 347, 383, 421, 461, 503, 547, 593, 641, 691, 743, 797, 853, 911, 971, 1033, 1097, 1163, 1231, 1301, 1373, 1447, 1523, 1601]


2.3: There are three other caboose numbers smaller than 41 and bigger than 3 that also have this property. Build code to search for them. I will provide a helpful prime reference list to check the generated primes against. Since the lower numbers are a bit floppy, start searching from 4 onwards.

Here are some general steps:
* Create an array of numbers from 4 to 40 (I hope this part's easy)
* Use your code from Exercise 2.2 to get the primes that come from each $x^2-x+p$. You'll have lots of sublists now, so tread carefully. Define this list of sublists as `e2_3a`.
* Use a conditional to kick out all the terms in the sublists that are not in the reference primes list, and define this as `e2_3b`.
* Convert both `e2_3a` and `e2_3b` to arrays, and use a conditional to see which terms are equal.
* Get the indices of all that are True, and modify these indices. (we aren't starting from 0, but starting from 4)

I'll leave it to you to convert these directions to actual code. Use the toolbox plenty, and make abundant use of comments (the hashtag)!

In [41]:
e2_numbers = np.arange(4,41)
e2_3a = [[x**2-x+y for x in np.arange(1,y)] for y in e2_numbers]
print(e2_3a)

[[4, 6, 10], [5, 7, 11, 17], [6, 8, 12, 18, 26], [7, 9, 13, 19, 27, 37], [8, 10, 14, 20, 28, 38, 50], [9, 11, 15, 21, 29, 39, 51, 65], [10, 12, 16, 22, 30, 40, 52, 66, 82], [11, 13, 17, 23, 31, 41, 53, 67, 83, 101], [12, 14, 18, 24, 32, 42, 54, 68, 84, 102, 122], [13, 15, 19, 25, 33, 43, 55, 69, 85, 103, 123, 145], [14, 16, 20, 26, 34, 44, 56, 70, 86, 104, 124, 146, 170], [15, 17, 21, 27, 35, 45, 57, 71, 87, 105, 125, 147, 171, 197], [16, 18, 22, 28, 36, 46, 58, 72, 88, 106, 126, 148, 172, 198, 226], [17, 19, 23, 29, 37, 47, 59, 73, 89, 107, 127, 149, 173, 199, 227, 257], [18, 20, 24, 30, 38, 48, 60, 74, 90, 108, 128, 150, 174, 200, 228, 258, 290], [19, 21, 25, 31, 39, 49, 61, 75, 91, 109, 129, 151, 175, 201, 229, 259, 291, 325], [20, 22, 26, 32, 40, 50, 62, 76, 92, 110, 130, 152, 176, 202, 230, 260, 292, 326, 362], [21, 23, 27, 33, 41, 51, 63, 77, 93, 111, 131, 153, 177, 203, 231, 261, 293, 327, 363, 401], [22, 24, 28, 34, 42, 52, 64, 78, 94, 112, 132, 154, 178, 204, 232, 262, 294, 32

In [42]:
reference_primes = [
    2, 3, 5, 7, 11, 13, 17, 19, 23, 29,
    31, 37, 41, 43, 47, 53, 59, 61, 67, 71,
    73, 79, 83, 89, 97, 101, 103, 107, 109, 113,
    127, 131, 137, 139, 149, 151, 157, 163, 167, 173,
    179, 181, 191, 193, 197, 199, 211, 223, 227, 229,
    233, 239, 241, 251, 257, 263, 269, 271, 277, 281,
    283, 293, 307, 311, 313, 317, 331, 337, 347, 349,
    353, 359, 367, 373, 379, 383, 389, 397, 401, 409,
    419, 421, 431, 433, 439, 443, 449, 457, 461, 463,
    467, 479, 487, 491, 499, 503, 509, 521, 523, 541,
    547, 557, 563, 569, 571, 577, 587, 593, 599, 601,
    607, 613, 617, 619, 631, 641, 643, 647, 653, 659,
    661, 673, 677, 683, 691, 701, 709, 719, 727, 733,
    739, 743, 751, 757, 761, 769, 773, 787, 797, 809,
    811, 821, 823, 827, 829, 839, 853, 857, 859, 863,
    877, 881, 883, 887, 907, 911, 919, 929, 937, 941,
    947, 953, 967, 971, 977, 983, 991, 997, 1009, 1013,
    1019, 1021, 1031, 1033, 1039, 1049, 1051, 1061, 1063, 1069,
    1087, 1091, 1093, 1097, 1103, 1109, 1117, 1123, 1129, 1151,
    1153, 1163, 1171, 1181, 1187, 1193, 1201, 1213, 1217, 1223,
    1229, 1231, 1237, 1249, 1259, 1277, 1279, 1283, 1289, 1291,
    1297, 1301, 1303, 1307, 1319, 1321, 1327, 1361, 1367, 1373,
    1381, 1399, 1409, 1423, 1427, 1429, 1433, 1439, 1447, 1451,
    1453, 1459, 1471, 1481, 1483, 1487, 1489, 1493, 1499, 1511,
    1523, 1531, 1543, 1549
]
e2_3b = [[x for x in y if x in reference_primes] for y in e2_3a]
print(e2_3b)

[[], [5, 7, 11, 17], [], [7, 13, 19, 37], [], [11, 29], [], [11, 13, 17, 23, 31, 41, 53, 67, 83, 101], [], [13, 19, 43, 103], [], [17, 71, 197], [], [17, 19, 23, 29, 37, 47, 59, 73, 89, 107, 127, 149, 173, 199, 227, 257], [], [19, 31, 61, 109, 151, 229], [], [23, 41, 131, 293, 401], [], [23, 29, 43, 53, 79, 113, 179, 233, 263, 443], [], [31, 37, 67, 97, 157, 181, 331, 367, 487, 577], [], [29, 47, 83, 137, 677], [], [29, 31, 41, 59, 71, 101, 139, 211, 239, 269, 409, 449, 491], [], [31, 37, 43, 61, 73, 103, 163, 241, 271, 337, 373, 631, 733, 787], [], [53, 89, 683], [], [37, 41, 47, 107, 167, 191, 307, 541, 587, 1091], [], [37, 43, 67, 79, 109, 127, 193, 277, 379, 457, 499, 739, 907, 967, 1093, 1297], [], [41, 59, 149, 311, 419, 1031, 1229], []]


In [47]:
corrects = make_array(e2_3a) == make_array(e2_3b)
corrects

array([[False,  True, False, False, False, False, False,  True, False,
        False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False]], dtype=bool)

In [52]:
results = np.where(corrects == True) # apparently this gives us two arrays? Unsure why the [0,0,0] shows up, but ignore that.
results

(array([0, 0, 0]), array([ 1,  7, 13]))

In [54]:
results[1]+4 # adjustment

array([ 5, 11, 17])

If you want to check your answers, here's a video on the Caboose Numbers!

https://www.youtube.com/watch?v=gM5uNcgn2NQ

### Exercise 3:
These exercises involve the use of strings. Try to predict the output in the same way as Exercise 1.

3.1: Here are a few examples of using the replace method to create new words out of 'apple'.

`apple = 'apple'`

`word_1 = 'h'+apple.replace('p', 'g')`

`word_2 = 'r'+apple.replace('p', 't')`

`word_3 = 'bed'+apple.replace('p', 'z')`

`word_4 = 's'+apple.replace('p', 'd')`

`word_5 = 'scr'+apple.replace('p', 'b')`

In [55]:
uncluttered = 'research' # try using .replace to get 5 words out of this

In [79]:
word_1 = 'r'+uncluttered.replace('es', '').replace('r', '')
word_1

'reach'

In [84]:
word_2 = uncluttered[-2:]+uncluttered[1]*2+uncluttered[2:4]
word_2

'cheese'

In [86]:
word_3 = uncluttered[1:3]+uncluttered[-2:]+'ew'
word_3

'eschew'

In [87]:
word_4 = uncluttered[-4:]+'er'
word_4

'archer'

In [88]:
word_5 = uncluttered[0]+uncluttered[4]+uncluttered[2]+uncluttered[-2]+uncluttered[4]+'l'
word_5

'rascal'

In [89]:
variable = 'decode'

In [90]:
word_1 = variable.replace('o', 'i')
word_1

'decide'

In [93]:
word_2 = variable.replace('d', 'r', 1).replace('o', 'or')+'d'
word_2

'recorded'

In [95]:
word_3 = variable.replace('de', 'al').replace('al', '', 1)
word_3

'coal'

In [96]:
word_4 = variable.replace('eco', 'ivi')
word_4

'divide'

In [97]:
word_5 = variable.replace('ode', 'oration')
word_5

'decoration'

3.2: Follow the variable names to get an output.

In [98]:
string_o_nums = '25439190243341193941203421982746422'

nine_to_four = string_o_nums.replace('9','4')

no_four = nine_to_four.replace('4','')

thirty_three_to_dash = no_four.replace('33','-')

three_to_slash = thirty_three_to_dash.replace('3', '/')

no_two = three_to_slash.replace('2', '')

when = no_two
when

'5/10-11/10/1876'

3.3: Follow the variable names to get an output.

In [99]:
gibberish = 'QnR5ZmxhR3VqM2xUYWhyUG8zPQAUB3CydBml2b3IBgU3CjYB2CBzc29yARm5YdU1nbjN1Um1qbnRy'

split_A = gibberish.split('A')

middle = split_A[1]

no_B = middle.replace('B','')

C_to_V = no_B.replace('C', 'V')

sixty_four = C_to_V
sixty_four

'U3Vydml2b3IgU3VjY2Vzc29y'

### Exercise 4: Index Practice
Indices are among the most widely-used coding concepts in a whole host of languages, and so it is imperative that you can employ and understand them fluently. These exercises employ the use of the soups list, as defined earlier. I've pasted it here for your convenience, and added a few more soups. *Don't hardcode the answers!*

In [101]:
soups = ['alphabet', 'chicken', 'noodle', 'italian wedding', 'tomato', 'mushroom', 'miso', 'clam chowder']

4.1: Use indices to get the fifth letter in the sixth word.

In [110]:
soups[5][4]

'r'

4.2: Use indices to get the ninth and tenth letters in the fourth word. Use the colon!

In [114]:
soups[3][9:11]

'ed'

4.3: There are two spaces in the soups variable. Get either one of the them using indices.

In [115]:
soups[3][7]

' '

4.4: Get the second letter in the second word.

In [116]:
soups[1][1]

'h'

4.5: Get the last two letters in the last word. (There's a hard way, and a *much* easier way.)

In [117]:
soups[-1][-2:]

'er'

4.6: Get the last three letters in the fourth word.

In [118]:
soups[3][-3:]

'ing'

## Conclusion
Hooray! This is the end of the exercises for lab 02. I had much fun with making this one. Feel free to leave feedback below about what could be changed or improved here.

Oh right, I almost forgot: if you have found the secret code, enter it below. If you get it right, you get an additional 2 extra extra credit credit points.